apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: digital-experience-production
  namespace: argocd

spec:
  project: default

  source:
    repoURL: https://github.com/atefChelaghma/pipe-gitops.git
    targetRevision: main
    path: k8s/overlays/production

  destination:
    server: https://kubernetes.default.svc
    namespace: production

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true