---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-secret
  namespace: production
spec:
  encryptedData:
    .dockerconfigjson: AgAJr9HD9rcocxiDoLTLDNFnPN0PZmhhGYzUSD30hSceb/ieQQP1Hn6/F6kq9vqV6mbblHsQwAJPFUWL4giw1AJWngZsbYN+UKbIT3TZqAoCAy2dHe+l+72V80TvBjo0CNFyh4THD2HrQxLtsCZdGbYPKnvhFDD5UlarguLdBx/4Dpc0498/zkN1FANl0Sq8UZqzbI8cjVSm6GcmizedN2YfEYXZXdpzWHiZRrzSQpAnJeXRVoxA00x37DMkXBUSu3ZP0Y/XicDsimKwqeBcKT3L7xp1UYHPBb3mw5cZOwDv5EtUJ8kHhXQIIvqLDiFKEJ036zu4HJmLbo2ioQH0W6kZt1r+jUCWLtUqKkuOTq57+3vxydHzRy3+7JncJu3PtwiK/gvCk7C+X7mUQaR0S+Pd2FMQ1YyOwLoiHmqb5h5tcli+iFoj9YNYdksX0B6PRgZRB9JT1X15GeuIw10vEqMTcsV/N8Y9nCsPPVbNyBzAH2pL8/8ArRtDJLqgyAHJP2RxteG3Wm+kufhfURmyxY0z1e3JvEMM6DdC6j6H1Bcatb78szFoVmzsJWql6B9FhAWW7CiplcpTDRx+KeYc9W2OEnutGrmcjcpTO6RQeeNUDIUn6ieXvGiH6bU+W8QaiFsUr2+fDmZ3O+tho+Hf14ApNS1cV+FlUUucLqDfBO8zqO60UgYvnyLizfB3FQ8dO8cfgpouqhdXU6bK2eIza0i3jfZuAVfRKy4FW3X8Nk0laWRgqW/uHFxFgYNR+qsfuTMK4pPDS6EqCuv9JLjql04dvhchPKrjXlZ3WqbK9+Zixmhv7HZSVMsp5263skkW9sEFqj81t1RfN3H7/Z5Mn7Xkh6KnAetncA5Rg8ouZ12akB3IvqZyd+0wrsmu1AOP0LpwSh61d+o4v/cmSczD7qlTwnqMi9ooXbAmVXSIpahw+HSFKvdy/4BC6fc=
  template:
    metadata:
      name: ghcr-secret
      namespace: production
    type: kubernetes.io/dockerconfigjson
