---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-secret
  namespace: preprod
spec:
  encryptedData:
    .dockerconfigjson: AgBX/8efG+ElC8zvm1sRVjYlxRFs43yX1mLsi67Leiut9dAavOeIexfeQsq6X8AaUhsZkEaMLQdM8alhq3ugZPs9lLs2b/CtZHkUwlIF1igimWHkoOOCvSf61ADKFrEwQJvxkwlcIraGcMRFDR4pGG6h0l/pvmKHBZCW0rkJXf6C1EYLxVwFMn6lPxzh3UriFs32aifkm9UY/bbOBPX7zY+24CVQ7RMcQuM+TgUuuecPi8Hf3SoXrLQEEylwe8Vwg/86G1UkCaT1MivNajvd/ki/skmWp1dUBPTMM9VTHQk1pKFzt4Cgpb1SiDbM+/eC1xaWM59uBAb3GeW7o7zuEWh/AIn2AxOxt8rgaT/bFCr3+7s68s+XWKvlbzW7U1ZL3CXPU5otGkeQshCngh9QH8xsvMzQFyZ2oaYY6n81u4RWusDtbDO0ifQIwwCYkgIKO2UQVWltAq641ZlGa5Dv+w5iV68f5/WzzgG0BxRHUHPIp1bCIbh4ApfQbr74OtVIKBT6HGs+Xhs1AkUhhttGs3hbMZt3n1SN407iwYnz65aSDFxRReCxsw803eCiN7NFYyhTHnZTQxla1mGEs/uJByd9f7t4jK5/2hwpR8OQgJ8YObSYUMADfOEAMfcuO6ErLbeHNXhzZ+PDKtNbRlVwD9+gmevTM3C8G337DzuOjYqAK1oa/Mc4BPsMQDKt6r0fnJG1YuJR6p20g3h7tHObHo0RTqayiLFBbE7dwpOKxb21rbWGHfNPSfk/5dPNoVFaeXoqJW0+iklPmxBVGtlfuuDoXhg3sEb3/PBySGKjUJmpi5a8Shfl8E/rv2lAnok4D5UfABTIRxJTTMOYkphfADF/9xU9J5vw6Mdc2eTyG+j2whp19eqAvYXvGlgFdDyvEzKn1Npxa35TFgz0IWdzlXRNJVQRawaoIB8FT49LszowdkQX9jwDTsfGtZA=
  template:
    metadata:
      name: ghcr-secret
      namespace: preprod
    type: kubernetes.io/dockerconfigjson
