---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-secret
  namespace: dev
spec:
  encryptedData:
    .dockerconfigjson: AgAf+Q2tayVzyeTce96ws4ivlpeznTs3K5uuoS6mzty5zIAwLZsMVJYew6pzG13xOm0hOGYFNlY4An2M908qcUlDYZTHVXKxukDdb/XsCAW7kbohrdw00kUSCzNVT5mb7tXDZYnn81WQ90z5x5BVoVyXbpZxOx0V7kX4KJU9rILyDLXIZuVEfUIOkxsyUxEazcL97io06fnvLwSlo4aoWPp3FyFyF5KXK6I8dLIZZ7bDd5BnbfgMaIx8aHQRPj8yP7hFKHeVkxgTqkU7s6HxZaPQCC5aBFzffCbbv5TDZ2mEtwmsA2py41wLSz3YqRngbEF6r+fAkUS9d5YiNZrGTY+8YR44WcRqMJxOkE7+UkQ6Edo4AQ7Z+fW8bfm6cyHN3sBtAse5n2Kx+Q0HIbhoAlGuvC7GrI+9si1p6f2NmA2eYjyfIXeD5MQCmzls1sC8csVoBi2MGaqJ+kZj/cEM9/sam0y6ATT2Oc+3dKDMp82JEMtwu203XpXiAf/SSHovx8VpB+2n5UV9QT2advrvR4Ax0hVmQBSTyM6zdjlE1ZQRX3i++GUCPuSKl4LzI1Y5mx5Rhz9lxpNSITAE4iqdboyclgnU7AIQYYkN4r3F927KqMJgPDyNPD4FVcEN6ALrIyftFeHMoNtVh5OsIennNHhuq2R3Mhl+zsRFYXnZMXV32jxofSIzKiVeKV1VfI5opH/WrVHr4A3AjAyq5S1sUJI8+47evLCQ/oIld6Zebxh4jniZIZmsMyEWwqaXddJyWBowWnhlDEesceMw/2aHYk1Bek7wIlEt2DqHUJhbabp4pwaLoX+4eML4MJ83GzTJ9SDkAKtPMsOzySQgg6yishgQyuo2vnxPZ/kjbBuhzAk3lpHd+yy+i9WUHs8l50J36SddEK9X1dO1wMU9MtNUeQFNFpXNHs0ZYKoVoKrmSrbnL6rihR3fr2FcnO4=
  template:
    metadata:
      name: ghcr-secret
      namespace: dev
    type: kubernetes.io/dockerconfigjson
