---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-secret
  namespace: dev
spec:
  encryptedData:
    .dockerconfigjson: AgA7oC+ISUBsHQk3ieu6rKSrF8mhuPCLLGTpgiBiaqXxDtDwelXjG6ql94FtGwrrdDinwgkWDJrPCtofGxfmnxuagMg+RYloVlrQBh3I01aT3lKtEkTZjVfwMrpGs28gUuSZ99A+M9o6KlqyVoqOJMhk/1wvvTQX6jy+qyFsKO1Ua786NOuoN1l6dvAJtyxIAZ61VNUTrkmmYieNhFu5365bcVK1t/9aqBfrQsF/udyZghjVK2lIfEZmTUuF0Tiv3It13RYuOXFafmf/W2JQWn8D/WW49/tlK4irmIyqyyBob0mzQ1Wg+IAUiqrPvg7/TkB0OUC2bZSqbdUJkE4C5FQ7FbsPsgySzH2xkLcnJzeyQh+2outhh1pP1thunqAMbnfUNva9La1iPLtJavA6LkpzC4juJzdSRUx2dSK14bcF4djnrEX/D0YfbmFK/jGupT1S63ZwMUM9vDn8mlN3sB+jiuPKLJqjeOxQBkwKalkX7yBoG2n4e9Di7dvD7R04dTk3CshYu4ewY3hoy3fxrkpB/uVR0RWY4YDVo9bbUZnpq5yUHy72acQLvZrn7Unp+nU9SqCiudzxGbHPgAc9W2O5XrElLlS52GTQz47PSQcULmPHpJ3gxBJ2DbwWWIWKB3HbrNBkebKTmsp0YJlBnVF+YXS6FMdUq3Uc1l7DBLNZrqB4hfL3zx0PtFAW7lkvL2hS7mGrX09bQDNMOKeyrX2wnzMlF1Pif1v7NTHoeuCi+JrjyJa38xahqbrKhODzJ08bxT7s7PVMSo+9GWXbpkHLEBdkN6h2h6LWpDsWN7ySaxSuPz2G+3xSfAiWvNids5kwaFEiqxi4SPkLqN+puuxGKWpnLVmv/idf6bSsdybYbg==
  template:
    metadata:
      name: ghcr-secret
      namespace: dev
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
    type: kubernetes.io/dockerconfigjson
