apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev

resources:
  - ../../base
  - ingress.yaml

patches:
  - path: patch.yaml

images:
  - name: ghcr.io/atefChelaghma/digital-experience
  - newTag: sha-4d77ca9
