apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev

resources:
- ../../base
- ingress.yaml

patches:
- path: patch.yaml

images:
- name: ghcr.io/atefchelaghma/digital-experience
  newName: ghcr.io/atefchelaghma/digital-experience
  newTag: sha-000f5af
